/PhysicalProperty/Management[]
/PhysicalProperty/Management[]/Address
/PhysicalProperty/Property[]/Identification/General_ID
/PhysicalProperty/Property[]/Identification/Address
/PhysicalProperty/Property[]/Identification/Phone
/PhysicalProperty/Property[]/Information/OfficeHour[]
/PhysicalProperty/Property[]/Information/Parking[]
/PhysicalProperty/Property[]/Information/Services
/PhysicalProperty/Property[]/Policy/Pet[]
/PhysicalProperty/Property[]/Floorplan[]/Room[]
/PhysicalProperty/Property[]/Floorplan[]/Deposit
/PhysicalProperty/Property[]/Floorplan[]/Amenities
/PhysicalProperty/Property[]/Floorplan[]/AirCon
/PhysicalProperty/Property[]/Floorplan[]/Fireplace
/PhysicalProperty/Property[]/Floorplan[]/Heat
/PhysicalProperty/Property[]/Floorplan[]/Range
/PhysicalProperty/Property[]/Amenities/Community
/PhysicalProperty/Property[]/Amenities/Floorplan
/PhysicalProperty/Property[]/Utility
/PhysicalProperty/Property[]/File[]
/PhysicalProperty/Property[]/Information/Parking
/PhysicalProperty/Property[]/Floorplan[]/Room
/PhysicalProperty/Property[]/Policy/Pet
/PhysicalProperty/Property[]/Amenities
/PhysicalProperty/Property[]/Identification/Fax
/PhysicalProperty/Property[]/Information/Services[]
/PhysicalProperty/Property[]/Identification/Phone[]
/PhysicalProperty/Property[]/Concession
/PhysicalProperty/Property[]/Floorplan[]/Concession
/PhysicalProperty/Property[]/Fee