/PhysicalProperty/Management/Address
/PhysicalProperty/Management/Phone
/PhysicalProperty/Management/Fax
/PhysicalProperty/Management/Contact/Phone
/PhysicalProperty/Management/Contact/Fax
/PhysicalProperty/Property[]/Identification/General_ID[]
/PhysicalProperty/Property[]/Identification/Address
/PhysicalProperty/Property[]/Identification/Phone
/PhysicalProperty/Property[]/Identification/Fax
/PhysicalProperty/Property[]/Information
/PhysicalProperty/Property[]/OnSiteContact/Phone
/PhysicalProperty/Property[]/OnSiteContact/Fax
/PhysicalProperty/Property[]/Fee
/PhysicalProperty/Property[]/Policy/Pet
/PhysicalProperty/Property[]/Building
/PhysicalProperty/Property[]/Floorplan[]/Room[]
/PhysicalProperty/Property[]/Floorplan[]/Deposit
/PhysicalProperty/Property[]/Floorplan[]/Amenities
/PhysicalProperty/Property[]/Floorplan[]/Fee
/PhysicalProperty/Property[]/Amenities/Community
/PhysicalProperty/Property[]/Identification/General_ID
/PhysicalProperty/Property[]/Identification/Phone[]
/PhysicalProperty/Property[]/Building[]
/PhysicalProperty/Property[]/Floorplan[]/Concession
/PhysicalProperty/Property[]/Amenities
/PhysicalProperty/Property[]/Concession