/PhysicalProperty/Management
/PhysicalProperty/Property[]/Identification/General_ID
/PhysicalProperty/Property[]/Identification/Address
/PhysicalProperty/Property[]/Identification/Phone
/PhysicalProperty/Property[]/Information/OfficeHour[]
/PhysicalProperty/Property[]/Information/Parking[]
/PhysicalProperty/Property[]/Accounting
/PhysicalProperty/Property[]/Payment/RemitTo
/PhysicalProperty/Property[]/Policy/Pet[]
/PhysicalProperty/Property[]/Floorplan[]/Room[]
/PhysicalProperty/Property[]/Floorplan[]/Deposit
/PhysicalProperty/Property[]/Floorplan[]/Fee
/PhysicalProperty/Property[]/Floorplan[]/Amenities
/PhysicalProperty/Property[]/Amenities/Community
/PhysicalProperty/Property[]/Amenities/Floorplan
/PhysicalProperty/Property[]/Amenities/General[]
/PhysicalProperty/Property[]/File[]
/PhysicalProperty/Property[]/Information/Parking
/PhysicalProperty/Property[]/Floorplan/Room[]
/PhysicalProperty/Property[]/Floorplan/Deposit
/PhysicalProperty/Property[]/Floorplan/Fee
/PhysicalProperty/Property[]/Floorplan/Amenities
/PhysicalProperty/Property[]/File
/PhysicalProperty/Property[]/Information